import Head from 'next/head'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ignite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={roboto.className}>
        <h1>Hello, world!</h1>
      </main>
    </>
  )
}
